# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: Rails.application.credentials.postgres_database_name
  username: Rails.application.credentials.postgres_user
  password: Rails.application.credentials.postgres_password
  host: Rails.application.credentials.postgres_uri
  port: 5432

test:
  <<: *default

production:
  <<: *default
  database: Rails.application.credentials.postgres_database_name
  username: Rails.application.credentials.postgres_user
  password: Rails.application.credentials.postgres_password
  host: Rails.application.credentials.postgres_uri
  port: 5432
